theme: jekyll-theme-minimal
title: "FNF Mod Center"
description: "FNFMod is a project that preserve mods of Friday Night Funkin'"
logo: "https://github.com/fnfmod/fnfmod.github.io/raw/master/fnfmod.png"
url: "http://fnfmod.github.io"
