theme: jekyll-theme-minimal
title: "FNF Mods Center"
description: "FNF Mods Center is a project that preserve mods of Friday Night Funkin'"
logo: "https://github.com/fnfmodscenter/fnfmodscenter.github.io/raw/master/fnfmodscenterlogo.png"
url: "http://fnfmodscenter.github.io"
